export const Jobs = [
  {
    title: "Frontend Developer",
    description: "Create beautiful user interfaces using React.",
    skills: ["React", "JavaScript", "HTML", "CSS"],
    budget: 5000,
  },
  {
    title: "Backend Developer",
    description: "Build scalable and efficient server-side applications.",
    skills: ["Node.js", "Express", "MongoDB"],
    budget: 6000,
  },
  {
    title: "UI/UX Designer",
    description: "Design intuitive and user-friendly interfaces.",
    skills: ["UI Design", "UX Design", "Adobe XD"],
    budget: 4500,
  },
  {
    title: "Data Scientist",
    description: "Analyze large datasets to extract meaningful insights.",
    skills: ["Python", "Machine Learning", "Statistics"],
    budget: 7000,
  },
  {
    title: "Mobile App Developer",
    description: "Develop cross-platform mobile applications.",
    skills: ["React Native", "iOS", "Android"],
    budget: 5500,
  },
  {
    title: "DevOps Engineer",
    description: "Optimize and automate deployment processes.",
    skills: ["Docker", "Kubernetes", "CI/CD"],
    budget: 6500,
  },
  {
    title: "Graphic Designer",
    description: "Create visually appealing graphics and layouts.",
    skills: ["Adobe Photoshop", "Illustrator", "Typography"],
    budget: 4000,
  },
  {
    title: "Full Stack Developer",
    description: "Work on both frontend and backend of applications.",
    skills: ["React", "Node.js", "MongoDB", "REST API"],
    budget: 6000,
  },
  {
    title: "Product Manager",
    description: "Manage product development and strategy.",
    skills: ["Product Management", "Agile", "Market Research"],
    budget: 7500,
  },
  {
    title: "Content Writer",
    description: "Create high-quality and engaging written content.",
    skills: ["Content Writing", "SEO", "Copywriting"],
    budget: 3500,
  },
  {
    title: "Network Engineer",
    description: "Design and maintain network infrastructure.",
    skills: ["Networking", "Cisco", "Firewalls"],
    budget: 5800,
  },
  {
    title: "Video Editor",
    description: "Edit and produce professional video content.",
    skills: ["Video Editing", "Adobe Premiere", "Final Cut Pro"],
    budget: 4200,
  },
  {
    title: "QA Tester",
    description: "Test software and identify bugs and issues.",
    skills: ["Software Testing", "Quality Assurance"],
    budget: 3200,
  },
  {
    title: "Digital Marketer",
    description: "Promote products and services online.",
    skills: ["Digital Marketing", "SEO", "Social Media"],
    budget: 4800,
  },
  {
    title: "Data Analyst",
    description: "Analyze data to provide insights for business decisions.",
    skills: ["Data Analysis", "SQL", "Excel"],
    budget: 5400,
  },
  {
    title: "UX Researcher",
    description: "Conduct user research to inform product design.",
    skills: ["User Research", "Usability Testing", "Prototyping"],
    budget: 4600,
  },
  {
    title: "E-commerce Manager",
    description: "Manage online store operations and sales.",
    skills: ["E-commerce", "Online Retail", "Marketing"],
    budget: 6800,
  },
  {
    title: "Technical Writer",
    description: "Create documentation for technical products.",
    skills: ["Technical Writing", "Documentation", "API"],
    budget: 3800,
  },
  {
    title: "Cybersecurity Analyst",
    description: "Protect systems and data from cyber threats.",
    skills: ["Cybersecurity", "Threat Detection", "Penetration Testing"],
    budget: 7200,
  },
  {
    title: "Project Manager",
    description: "Plan and oversee project execution.",
    skills: ["Project Management", "Agile", "Team Collaboration"],
    budget: 6700,
  },
  {
    title: "Sales Representative",
    description: "Sell products or services to potential clients.",
    skills: ["Sales", "Negotiation", "Client Relationship"],
    budget: 3000,
  },
];
