export const allVirtualAssistantSkills = [
  "Email Management",
  "Calendar Scheduling",
  "Data Entry",
  "File Organization",
  "Travel Planning",
  "Appointment Setting",
  "Customer Support",
  "Client Communication",
  "Phone Calls",
  "Live Chat Support",
  "Email Correspondence",
  "Proofreading",
  "Social Media Management",
  "Content Creation",
  "Social Media Posting",
  "Community Engagement",
  "Analytics Tracking",
  "Influencer Outreach",
  "Content Writing",
  "Blog Post Creation",
  "Copywriting",
  "Editing and Proofreading",
  "Research",
  "Content Calendar Management",
  "Graphic Design",
  "Image Editing",
  "Logo Design",
  "Infographic Creation",
  "Presentation Design",
  "Visual Content Creation",
  "Website Maintenance",
  "WordPress Management",
  "Basic HTML/CSS",
  "Data Analysis",
  "Research",
  "Online Research",
  "Product Listing",
  "Inventory Management",
  "Order Processing",
  "Customer Support",
  "E-commerce Platform Management",
  "Product Research",
  "Task Coordination",
  "Project Planning",
  "Team Communication",
  "Task Tracking",
  "Deadline Management",
  "Project Documentation",
];
